config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :articles do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  belongs_to :user
  # アップローダ
  mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    articles_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.page(params[:page]).per(5).order("created_at DESC")
  end

  def show
    @comment = Comment.new
    @comments = @article.comments.includes(:user)
  end

  def new
    @article = Article.new
  end

  def create
    Article.create(article_params)
    redirect_to_msg("新しい記事が投稿されました。")
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to_msg("記事が編集されました。")
  end

  def destroy
    @article.destroy
    redirect_to_msg("記事が削除されました。")
  end

  private
  def article_params
    params.require(:article).permit(:title, :content, :image).merge(user_id: current_user.id)
  end

  def redirect_to_msg(msg)
    redirect_to ({ controller: :users, action: :show, id: current_user.id }), notice: msg
  end

  def set_article
    @article= Article.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    Comment.create(create_params)
    redirect_to controller: :articles, action: :show, id: params[:article_id]
  end

  def create_params
    params.require(:comment).permit(:comment_content).merge(article_id: params[:article_id], user_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render :layout => 'home'
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @articles = @user.articles.order('updated_at DESC')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_has?(instance)
    user_signed_in? && current_user == instance.user
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_articles_cards.html.erb
<div class="card mt-5 mb-5 shadow-sm">
  <div class="row no-gutters">
    <div class="col-md-6">
      <%= image_tag article.image_url, class: "card-img shadow-sm", alt: "#{article.title}" %>
    </div>
    <div class="col-md-6">
      <div class="card-body">
        <h5><%= link_to article.user.name, user_path(article.user.id), class: "badge badge-pill badge-info float-right" %></h5>
        <h1 class="card-title"><%= article.title %></h1>
        <hr>
        <p class="card-text text-truncate"><%= article.content %></p>
        <p class="card-text"><small class="text-muted"><%= article.created_at %> 投稿</small></p>
        <%= link_to "記事へ", article_path(article.id), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<div class="form-group">
  <div class="custom-file">
    <%= article.file_field :image, id: "img", class: "custom-file-input" %>
    <label class="custom-file-label" for="img">画像を選択</label>
  </div>
</div>
<div class="form-group">
  <label for="title">タイトル</label>
  <%= article.text_field :title, id: "title", class: "form-control" %>
</div>
<div class="form-group">
  <label for="content">内容</label>
  <%= article.text_area :content, id: "content", rows: "8", class: "form-control" %>
</div>
<div class="text-right">
  <%= article.submit act_btn, class: "btn btn-primary" %>
</div>

app/views/articles/edit.html.erb
<div class="mt-5">
	<%= form_for @article, url:{ action: 'update', method: 'patch' } do |article|%>
		<%= render partial: "form", locals: { article: article, act_btn: "反映" } %>
	<% end %>
</div>

app/views/articles/index.html.erb
<%# コンテンツ %>
<% @articles.each do |article| %>
  <%= render partial: "articles_cards", locals: { article: article }  %>
<% end %>
<%# ペジネーション %>
<%= paginate @articles %>

app/views/articles/new.html.erb
<div class="mt-5">
	<%= form_for @article, url:{ action: 'create', method: 'post' } do |article|%>
		<%= render partial: "form", locals: { article: article, act_btn: "投稿" } %>
	<% end %>
</div>

app/views/articles/show.html.erb
<div class="card mt-5 mb-5 shadow">
	<%= image_tag @article.image_url, class: "card-img-top", style: "height: 300px; object-fit: cover;" %>
	<div class="card-body">
		<h5 class="card-title"><%= @article.title %></h5>
		<p class="card-text"><%= simple_format(@article.content) %></p>
		<p class="card-text"><small class="text-muted"><%= @article.updated_at %> 最終更新日</small></p>
	</div>
</div>
<div class="card mt-5 mb-5 shadow">
  <div class="card-header">
    コメント一覧
  </div>
	<div class="comment p-3">
		<% @comments.each do |comment| %>
		<div class="card mb-3">
			<div class="card-body">
				<h5 class="card-title"><%= comment.user.name%></h5>
				<p class="card-text"><%= comment.comment_content %></p>
				<p class="blockquote-footer"><%= comment.created_at %></p>
			</div>
		</div>
		<% end %>
	</div>

	<div class="card-footer">
		<%= form_for [@article, @comment] do |form| %>
		<div class="input-group mt-3 mb-3">
			<%= form.text_field :comment_content, class: "form-control", placeholder: "コメント" %>
			<div class="input-group-append">
				<% if user_signed_in? %>
					<%= form.submit "コメント投稿", class: "btn btn-primary" %>
				<% else %>
					<span data-toggle="tooltip" title="投稿するにはログインする必要があります">
						<button class="btn btn-primary" style="pointer-events: none;border-radius: 0px 5px 5px 0;" type="button" disabled>コメント投稿</button>
					</span>
				<% end %>
			</div>
		</div>
		<% end %>
	</div>
</div>
<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
</script>

app/views/home/index.html.erb
<div class="bg">
  <div class="container h-100">
    <div class="row align-items-center h-100">
        <div class="mx-auto text-dark text-center">
          <h1 class="display-1">Blog Us</h1>
          <p class="display-4">皆のブログ</p>
          <% unless user_signed_in? %>
            <%= link_to "仲間になろう", new_user_registration_path, class: "btn btn-primary btn-lg shadow" %>
          <% end %>
          <%= link_to "記事一覧", articles_path, class: "btn btn-info btn-lg shadow" %>
        </div>
    </div>
</div>
</div>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
	<div class="toast ml-auto mt-5" role="alert" data-delay="4000" data-autohide="true" style="position:absolute; top:100px; right:100px; z-index: 2;">
			<div class="toast-header">
					<strong class="mr-auto text-success">Success</strong>
					<small class="text-muted">now</small>
					<button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
							<span aria-hidden="true">×</span>
					</button>
			</div>
			<div class="toast-body">
				<%= flash[:notice] %>
			</div>
	</div>
	<script>
		$(document).ready(function () {
			$('.toast').toast('show');
			$('.tooltip').tooltip('show');
		})
	</script>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg shadow navbar-light bg-light fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">BlogUs</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item active mr-3">
          <%= link_to "投稿", new_article_path, class: "btn btn-primary" %>
        </li>
        <li class="nav-item active mr-3">
          <%= link_to "記事一覧", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <div class="btn-group active">
            <%= link_to current_user.name, user_path(current_user.id), class: "nav-link" %>
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuReference">
              <%= link_to "アカウント", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "ログアウト", destroy_user_session_path, method: "delete", class: "dropdown-item text-danger" %>
            </div>
          </div>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "記事一覧", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
  </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogUs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <%= render partial: "layouts/flash" %>
    <div class="container pt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogUs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <%= render partial: "layouts/flash" %>
    <%= yield %>
  </body>
</html>

app/views/users/_user_article_cards.html.erb
<div class="col-md-6 col-lg-4 card-deck mb-3">
		<div class="card shadow">
			<%= link_to article_path(article.id) do %>
				<%= image_tag article.image_url, class: "card-img-top" %>
			<% end %>
			<div class="card-body">
				<h5 class="card-title"><%= article.title %></h5>
				<p class="card-text text-truncate" style="max-width: 180px;"><%= article.content %></p>
				<% if current_user_has?(article) %>
				<div class="btn-group float-right">
					<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						操作
					</button>
					<div class="dropdown-menu dropdown-menu-right">
						<%= link_to '編集', edit_article_path(article.id), class: "dropdown-item text-primary" %>
						<div class="dropdown-divider"></div>
						<%= link_to '削除', article_path(article.id), method: :delete, class: "dropdown-item text-danger",
						data: { confirm: "本当に「<strong>#{article.title}</strong>」を削除してよろしいですか？", 
						commit: "削除する", cancel: "やっぱりやめる" }, title: "削除の確認" %>
					</div>
				</div>
				<% end %>
			</div>
		</div>
	</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードを忘れた方", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1 class="mt-5"><%= @user.name %>の部屋</h1>
<div class="row mt-5">
	<% @articles.each do |article| %>
		<%= render partial: "user_article_cards", locals: { article: article } %>
	<% end %>
</div>